version: '3.8'

services:
  migrate:
    image: bookstore-api:latest
    build: .
    volumes:
      - sqlite:/app/db
    command: python3 manage.py migrate


  api:
    image: bookstore-api:latest
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - sqlite:/app/db
    depends_on:
      - migrate

volumes:
  sqlite:

