# Generated by Django 4.2 on 2023-04-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
        ("stores", "0003_store_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookstore",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_amounts_in_store",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookstore",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_amounts",
                to="stores.store",
            ),
        ),
    ]
