# Generated by Django 4.2 on 2023-04-09 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("birth_date", models.DateField(default=datetime.datetime.now)),
                ("is_alive", models.BooleanField()),
            ],
        ),
    ]
